from setuptools import setup

setup(name='pytest-report-push',
      use_scm_version={
          'version_scheme': 'post-release',
          'local_scheme': 'node-and-date',
          "relative_to": __file__,
          "root": "..",
      },
      version='0.0.1',
      description='pytest plugin for push report',
      long_description=open('README.md').read(),
      author='lunz1207',
      author_email='lunz1207@gmail.com',
      url='https://github.com/no8ge/files/pytest-plugin',
      packages=["pytest_report_push"],
      package_dir={"pytest_report_push": "src"},
      entry_points={"pytest11": [
          "pytest_report_push = pytest_report_push"]},
      setup_requires=['setuptools_scm'],
      install_requires=[
          'pytest>=3.6',
          'anyio==3.6.2',
          'asgiref==3.5.2',
          'attrs==22.1.0',
          'autopep8==1.6.0',
          'certifi==2022.9.24',
          'charset-normalizer==2.1.1',
          'click==8.1.3',
          'fastapi==0.78.0',
          'h11==0.14.0',
          'httptools==0.5.0',
          'idna==3.4',
          'iniconfig==1.1.1',
          'loguru==0.6.0',
          'minio==7.1.12',
          'packaging==21.3',
          'pluggy==1.0.0',
          'py==1.11.0',
          'pycodestyle==2.9.1',
          'pydantic==1.10.2',
          'pyparsing==3.0.9',
          'pytest==7.1.2',
          'python-dotenv==0.21.0',
          'python-multipart==0.0.5',
          'PyYAML==6.0',
          'requests==2.28.1',
          'requests-toolbelt==0.9.1',
          'six==1.16.0',
          'sniffio==1.3.0',
          'starlette==0.19.1',
          'toml==0.10.2',
          'tomli==2.0.1',
          'typing_extensions==4.4.0',
          'urllib3==1.26.12',
          'uvicorn==0.17.6',
          'uvloop==0.17.0',
          'watchgod==0.8.2',
          'websockets==10.4',
      ],
      license='Mozilla Public License 2.0 (MPL 2.0)',
      keywords='pytest pytest report_push',
      python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
      classifiers=[
          'Development Status :: 5 - Production/Stable',
          'Framework :: Pytest',
          'Intended Audience :: Developers',
          'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
          'Operating System :: POSIX',
          'Operating System :: Microsoft :: Windows',
          'Operating System :: MacOS :: MacOS X',
          'Topic :: Software Development :: Quality Assurance',
          'Topic :: Software Development :: Testing',
          'Topic :: Utilities',
          'Programming Language :: Python',
          'Programming Language :: Python :: 2.7',
          'Programming Language :: Python :: 3.5',
          'Programming Language :: Python :: 3.6',
          'Programming Language :: Python :: 3.7',
          'Programming Language :: Python :: 3.8',
          'Programming Language :: Python :: 3.9',
      ])
